language: python
python:
  - "2.7"
install:
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb
  - vagrant --version

  - sudo vagrant plugin install vagrant-google
  - sudo vagrant plugin install inifile
  - sudo vagrant plugin install vagrant-hostmanager

script:
  - git clone https://github.com/wepay/ducktape.git
  - cd ducktape && python setup.py install && cd ..
  - sudo vagrant up --provider=google --no-parallel # The error is only presented when executing vagrant up
  - sudo vagrant ssh -c "echo 'hello world!'"
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy